import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Welcome to whatsweatherdoing.com</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to{" "}
					<a href="https://whatsweatherdoing.com">whatsweatherdoing.com</a>
				</h1>

				<p className={styles.description}>
					All your weather needs at tap of one button.
				</p>

				<div className={styles.grid}> </div>
			</main>

			<footer className={styles.footer}>
				<a href="/" target="_blank" rel="noopener noreferrer">
					Copyright 2022
					<span className={styles.logo}>
						<Image
							src="/safari-pinned-tab.svg"
							alt="whatsweatherdoing.com"
							width={72}
							height={16}
						/>
					</span>
				</a>

				<Link href="/privacy">
					<a>Privacy</a>
				</Link>
			</footer>
		</div>
	);
};

export default Home;
