import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Privacy: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Privacy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Privacy Policy</h1>
				<p>Whats weather doing application requires your location to enable it to call an open weather api.</p>
				<p>The Open Weather API: <Link href={'https://openweathermap.org/current'}>click here to read more</Link>. This API will return the weather in your current location, Whats weather doing application provides only your Latitude and Longitude to the API, nothing else. 
				</p>
				<p>We do not collect any personal data or share it.</p>
				<p>The location data is only used once and while using the feature of getting the weather in the users location. This can be turned off at any time.</p>
			</main>

			<footer className={styles.footer}>
				<a href="/" target="_blank" rel="noopener noreferrer">
					Copyright 2022
					<span className={styles.logo}>
						<Image
							src="/safari-pinned-tab.svg"
							alt="whatsweatherdoing.com"
							width={72}
							height={16}
						/>
					</span>
				</a>

				<Link href="/privacy">
					<a>Privacy</a>
				</Link>

				<Link href="/">
					<a>Home</a>
				</Link>
			</footer>
		</div>
	);
};

export default Privacy;
